name: technical_assessment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  retrofit: ^3.0.1+1
  dio: ^4.0.6


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true